/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Address {
  'city' : string,
  'district' : string,
  'state' : string,
  'fullAddress' : string,
  'pincode' : string,
}
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Branch {
  'id' : bigint,
  'manager' : Principal,
  'name' : string,
  'createdAt' : bigint,
  'memberCount' : bigint,
  'isActive' : boolean,
  'district' : string,
  'state' : string,
  'address' : Address,
}
export type ExternalBlob = Uint8Array;
export interface GalleryItem {
  'id' : bigint,
  'createdAt' : bigint,
  'isActive' : boolean,
  'caption' : string,
  'category' : string,
  'image' : ExternalBlob,
}
export interface Notice {
  'id' : bigint,
  'noticeType' : NoticeType,
  'title' : string,
  'content' : string,
  'createdAt' : bigint,
  'publishedBy' : Principal,
  'isActive' : boolean,
}
export type NoticeType = { 'notice' : null } |
  { 'news' : null };
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile {
  'pan' : [] | [string],
  'status' : string,
  'bankDetails' : [] | [string],
  'name' : string,
  'role' : string,
  'aadhaar' : [] | [string],
  'address' : [] | [Address],
  'mobile' : string,
  'registeredAt' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBranch' : ActorMethod<
    [string, string, string, Address, Principal],
    bigint
  >,
  'createNotice' : ActorMethod<[string, string, NoticeType], bigint>,
  'deleteBranch' : ActorMethod<[bigint], undefined>,
  'deleteGalleryItem' : ActorMethod<[bigint], undefined>,
  'deleteNotice' : ActorMethod<[bigint], undefined>,
  'getBranch' : ActorMethod<[bigint], Branch>,
  'getBranches' : ActorMethod<[], Array<Branch>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGallery' : ActorMethod<[], Array<GalleryItem>>,
  'getNotice' : ActorMethod<[bigint], Notice>,
  'getNotices' : ActorMethod<[], Array<Notice>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'updateBranch' : ActorMethod<
    [bigint, string, string, string, Address, Principal, bigint, boolean],
    undefined
  >,
  'updateGalleryItem' : ActorMethod<
    [bigint, string, string, boolean],
    undefined
  >,
  'updateNotice' : ActorMethod<
    [bigint, string, string, NoticeType, boolean],
    undefined
  >,
  'uploadGalleryItem' : ActorMethod<[ExternalBlob, string, string], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];