/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Address = IDL.Record({
  'city' : IDL.Text,
  'district' : IDL.Text,
  'state' : IDL.Text,
  'fullAddress' : IDL.Text,
  'pincode' : IDL.Text,
});
export const NoticeType = IDL.Variant({
  'notice' : IDL.Null,
  'news' : IDL.Null,
});
export const Branch = IDL.Record({
  'id' : IDL.Nat,
  'manager' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'memberCount' : IDL.Nat,
  'isActive' : IDL.Bool,
  'district' : IDL.Text,
  'state' : IDL.Text,
  'address' : Address,
});
export const UserProfile = IDL.Record({
  'pan' : IDL.Opt(IDL.Text),
  'status' : IDL.Text,
  'bankDetails' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'role' : IDL.Text,
  'aadhaar' : IDL.Opt(IDL.Text),
  'address' : IDL.Opt(Address),
  'mobile' : IDL.Text,
  'registeredAt' : IDL.Int,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const GalleryItem = IDL.Record({
  'id' : IDL.Nat,
  'createdAt' : IDL.Int,
  'isActive' : IDL.Bool,
  'caption' : IDL.Text,
  'category' : IDL.Text,
  'image' : ExternalBlob,
});
export const Notice = IDL.Record({
  'id' : IDL.Nat,
  'noticeType' : NoticeType,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : IDL.Int,
  'publishedBy' : IDL.Principal,
  'isActive' : IDL.Bool,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBranch' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, Address, IDL.Principal],
      [IDL.Nat],
      [],
    ),
  'createNotice' : IDL.Func([IDL.Text, IDL.Text, NoticeType], [IDL.Nat], []),
  'deleteBranch' : IDL.Func([IDL.Nat], [], []),
  'deleteGalleryItem' : IDL.Func([IDL.Nat], [], []),
  'deleteNotice' : IDL.Func([IDL.Nat], [], []),
  'getBranch' : IDL.Func([IDL.Nat], [Branch], ['query']),
  'getBranches' : IDL.Func([], [IDL.Vec(Branch)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGallery' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
  'getNotice' : IDL.Func([IDL.Nat], [Notice], ['query']),
  'getNotices' : IDL.Func([], [IDL.Vec(Notice)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'requestApproval' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'updateBranch' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        Address,
        IDL.Principal,
        IDL.Nat,
        IDL.Bool,
      ],
      [],
      [],
    ),
  'updateGalleryItem' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Bool],
      [],
      [],
    ),
  'updateNotice' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, NoticeType, IDL.Bool],
      [],
      [],
    ),
  'uploadGalleryItem' : IDL.Func(
      [ExternalBlob, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Address = IDL.Record({
    'city' : IDL.Text,
    'district' : IDL.Text,
    'state' : IDL.Text,
    'fullAddress' : IDL.Text,
    'pincode' : IDL.Text,
  });
  const NoticeType = IDL.Variant({ 'notice' : IDL.Null, 'news' : IDL.Null });
  const Branch = IDL.Record({
    'id' : IDL.Nat,
    'manager' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'memberCount' : IDL.Nat,
    'isActive' : IDL.Bool,
    'district' : IDL.Text,
    'state' : IDL.Text,
    'address' : Address,
  });
  const UserProfile = IDL.Record({
    'pan' : IDL.Opt(IDL.Text),
    'status' : IDL.Text,
    'bankDetails' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'role' : IDL.Text,
    'aadhaar' : IDL.Opt(IDL.Text),
    'address' : IDL.Opt(Address),
    'mobile' : IDL.Text,
    'registeredAt' : IDL.Int,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const GalleryItem = IDL.Record({
    'id' : IDL.Nat,
    'createdAt' : IDL.Int,
    'isActive' : IDL.Bool,
    'caption' : IDL.Text,
    'category' : IDL.Text,
    'image' : ExternalBlob,
  });
  const Notice = IDL.Record({
    'id' : IDL.Nat,
    'noticeType' : NoticeType,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : IDL.Int,
    'publishedBy' : IDL.Principal,
    'isActive' : IDL.Bool,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBranch' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, Address, IDL.Principal],
        [IDL.Nat],
        [],
      ),
    'createNotice' : IDL.Func([IDL.Text, IDL.Text, NoticeType], [IDL.Nat], []),
    'deleteBranch' : IDL.Func([IDL.Nat], [], []),
    'deleteGalleryItem' : IDL.Func([IDL.Nat], [], []),
    'deleteNotice' : IDL.Func([IDL.Nat], [], []),
    'getBranch' : IDL.Func([IDL.Nat], [Branch], ['query']),
    'getBranches' : IDL.Func([], [IDL.Vec(Branch)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGallery' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
    'getNotice' : IDL.Func([IDL.Nat], [Notice], ['query']),
    'getNotices' : IDL.Func([], [IDL.Vec(Notice)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'requestApproval' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'updateBranch' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          Address,
          IDL.Principal,
          IDL.Nat,
          IDL.Bool,
        ],
        [],
        [],
      ),
    'updateGalleryItem' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Bool],
        [],
        [],
      ),
    'updateNotice' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, NoticeType, IDL.Bool],
        [],
        [],
      ),
    'uploadGalleryItem' : IDL.Func(
        [ExternalBlob, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };